# Configurações do servidor
server.port=8088
server.servlet.context-path=/

# Configurações do banco de dados H2
spring.datasource.url=jdbc:h2:mem:produtosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# H2 Console (opcional para debug)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging
logging.level.root=INFO
logging.level.com.demo=DEBUG

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.indent-output=true

# Aplicação
app.name=Springboot API Produto
app.version=1.0.0
